### PR TITLE
Improved tools: stegano-tools

### PR DESCRIPTION
**Pull request by dhondta**
Fixed symlinks to tools
Added `uninstall` file

### CODE REVIEW

**Comment by zardus** [comment]
This seems like it would only work when ctftools is installed as the ctf user?

**Comment by dhondta** [comment]
Indeed. I can replace occurrences of `/home/ctf` with `$HOME` if you want...

**Comment by zardus** [comment]
I think that's a good initial solution, yep!

**Comment by dhondta** [comment]
OK, done !

**Comment by zardus** [comment]
Thanks!

**Pull request merged**
