### PR TITLE
Updating a few installers.

### PR DESCRIPTION
**Pull request by hal3002**
Includes a metasploit installer, updated a few packages to use the correct google code or github URL, added a few required packages, and added a JDK installer for Android-sdk.

### CODE REVIEW

**Comment by zardus** [comment]
I like most of the other changes, but doesn't metasploit require root and do a bunch of other global stuff? So far, I've tried to keep every individual installed tool confined to their own directories...

**Comment by hal3002** [comment]
Yeah, sorry about that.  I read that after my initial commit and meant to remove the metasploit addition until I could figure out how to make it local.  I've removed the installer for now.

**Comment by hal3002** [comment]
Also, if you want to wait for a bit I'm updating the reveng package as well.

**Comment by hal3002** [comment]
Woohoo. Looks like everything is building now.

**Comment by zardus** [comment]
Awesome! Thank you!

**Pull request merged**
