### PR TITLE
"full-upgrade" to upgrade only installed tools

### LINKED ISSUE #7: ctf-tools can't update existing installs
something like

`manage-tools upgrade` to update to the latest version of tools would be really awesome. Some things like `afl-fuzz` and `radare2` update very frequently, and keeping in sync would be helpful.

### PR DESCRIPTION
**Pull request by f0rki**
just a quick thing I whipped up. 

Maybe this is better suited as `manage-tools upgrade all`?

Fixes #7

### CODE REVIEW

**Comment by zardus** [comment]
I do like `manage-tools upgrade all-installed` or something better, yeah... We could handle it the same way we handle `all` and make it general for other actions as well (though it makes the most sense for `upgrade`).

That being said, I'm not super picky on this. If you don't have time to do it that way, we can go with this method here.

**Comment by f0rki** [comment]
I will do it next week.

On December 1, 2017 10:27:05 PM GMT+01:00, Yan <notifications@github.com> wrote:
>I do like `manage-tools upgrade all-installed` or something better,
>yeah... We could handle it the same way we handle `all` and make it
>general for other actions as well (though it makes the most sense for
>`upgrade`).
>
>That being said, I'm not super picky on this. If you don't have time to
>do it that way, we can go with this method here.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/zardus/ctf-tools/pull/152#issuecomment-348618623

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by f0rki** [comment]
what do you think of simply `manage-tools upgrade` additionally to `manage-tools upgrade all`?

I think `upgrade all-installed` is too cumbersome to type. `upgrade` makes only sense on already installed tools anyway.

**Comment by zardus** [comment]
Sounds good!

**Comment by f0rki** [comment]
Sorry it took so long. It should be nicer to use now. You can do
```
manage-tools upgrade
```
or
```
manage-tools upgrade all
```

to upgrade all installed tools. Similarly the `bin` and `reinstall` commands also work only on the tools already installed.

I also added a function `verify_tool_sanity`, which checks whether the current `TOOL` variable is actually a directory in the ctf-tools repo, is not empty and not `"all"` (because it's handled somewhere else in the code).

**Comment by zardus** [comment]
Looks good!

**Pull request merged**
