### PR TITLE
License added: BSD2

### PR DESCRIPTION
**Pull request by zwimer**

### CODE REVIEW

**Comment by zardus** [comment]
Paging @f0rki @raildex1 @hal3002 @boogy @ret2libc @zwimer @rhelmot @crowell @NickStephens @subwire @eugenekolo @cao @salls @nebirhos @stasinopoulos @lujun9972 @cub01d @pwnslinger @richard-clifford @Ga-ryo @eboderas @Edznux @hackertron @akshaykrishnan @cspensky @antoniobianchi333 @kapravel @jcorina!

After several requests to put a real license on this repo for some reason, this PR will switch the license to BSD. I want to make sure all the contributors are okay with it. If you are *not* okay with it, please let me know within a week! If you *are* okay with it, to keep the number of notifications to everyone to a minimum (since everyone is @-mentioned on this PR), sit tight :-)

**Comment by hackertron** [comment]
No issues !!

**Comment by cao** [comment]
I'd prefer 3-clause over 2-clause BSD, to keep the non-endorsement clause (for future's sake):

> 3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

**Comment by lujun9972** [comment]
I am OK

**Comment by zardus** [comment]
I'm fine with the 3-clause. @zwimer, can you push that? If anyone is _not_ fine with the 3-clause, speak up in the next week :-)

**Comment by zardus** [comment]
:+1:

**Pull request merged**
