### PR TITLE
Add append to gdbinit

### PR DESCRIPTION
**Pull request by raildex1**
Cost me a lot of time in CSAW trying to figure this out (sadly)...

Let my loss be your gain :)

### CODE REVIEW

**Comment by zardus** [comment]
lol, sorry about that :-)

Could you change it to not hardcode the `~/ctf-tools/peda/peda` path? Maybe replace it with `$PWD/peda`?

Hope CSAW went well for you!

**Comment by raildex1** [comment]
When I wake up - haven't slept!

**Comment by raildex1** [comment]
Done - works perfectly now.

**Comment by zardus** [comment]
Thanks!

**Pull request merged**
